// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBIBycGbVATHPldtet555qkwTSz9FLMWo',
    appId: '1:308985020536:web:0e94a91fb91a320bc36d8d',
    messagingSenderId: '308985020536',
    projectId: 'fb-68854',
    authDomain: 'fb-68854.firebaseapp.com',
    storageBucket: 'fb-68854.firebasestorage.app',
    measurementId: 'G-MJ23SLBGLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAldcIoOpMBJxo35v5g_oe7Y8K9QgAPfk',
    appId: '1:308985020536:android:898d33a18287e3efc36d8d',
    messagingSenderId: '308985020536',
    projectId: 'fb-68854',
    storageBucket: 'fb-68854.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtJaEslKtIrt5JZ1oG95v-7-KUvR0IXBQ',
    appId: '1:308985020536:ios:f998d39e86c4e8f4c36d8d',
    messagingSenderId: '308985020536',
    projectId: 'fb-68854',
    storageBucket: 'fb-68854.firebasestorage.app',
    iosBundleId: 'com.example.googleSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBIBycGbVATHPldtet555qkwTSz9FLMWo',
    appId: '1:308985020536:web:203b3e59b3b88dafc36d8d',
    messagingSenderId: '308985020536',
    projectId: 'fb-68854',
    authDomain: 'fb-68854.firebaseapp.com',
    storageBucket: 'fb-68854.firebasestorage.app',
    measurementId: 'G-X8DC728CSH',
  );
}
